version: 2
jobs:
  lint:
    working_directory: ~/circleci/circleci
    docker:
      - image: bufbuild/buf:1.1.1
    steps:
      - checkout:
          path: ~/circleci
      - run: buf lint
  breaking:
    working_directory: ~/circleci/circleci
    docker:
      - image: bufbuild/buf:1.1.1
    steps:
      - checkout:
          path: ~/circleci
      - run: buf breaking --against https://github.com/bufbuild/buf-examples.git#branch=main,ref=HEAD~1,subdir=circleci

workflows:
  version: 2
  protobuf_check:
    jobs:
      - lint
      - breaking
